version: 1.1.1
main: com.hhyusein.plugin.Main
name: PlayerFlight
author: xMrShadyx
description: This plugin gives, flight ability to non OP player.
api-version: 1.17

commands:
  pfly:
    aliases: []
    description: Free fly for non-OP players.

    